from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest

FIXTURES = Path(__file__).parent / "fixtures"
ARTIFACTS = Path(__file__).parent / "artifacts"


def pytest_sessionstart(session):
    """Build the PDF fixtures if they're missing, so a fresh clone can just run
    pytest."""
    if not (FIXTURES / "tagged_with_figures.pdf").exists():
        subprocess.run(
            [sys.executable, str(FIXTURES / "generate_fixtures.py")],
            check=True,
            capture_output=True,
        )

    # Ensure artifacts directory exists for debug output
    ARTIFACTS.mkdir(exist_ok=True)

    # Clean stale debug artifacts from previous runs
    # (Only overlays are generated — they indicate failures, so stale ones mislead)
    for old_artifact in ARTIFACTS.glob("*.png"):
        old_artifact.unlink()


def _read(name: str) -> bytes:
    return (FIXTURES / name).read_bytes()


@pytest.fixture
def tagged_with_figures() -> bytes:
    """2 pages, one /Figure each, neither has /Alt. The happy path."""
    return _read("tagged_with_figures.pdf")


@pytest.fixture
def tagged_alt_present() -> bytes:
    """1 page, one /Figure that already has /Alt."""
    return _read("tagged_alt_present.pdf")


@pytest.fixture
def tagged_no_figures() -> bytes:
    """Tagged, text only — nothing to remediate."""
    return _read("tagged_no_figures.pdf")


@pytest.fixture
def untagged_scanned() -> bytes:
    """No structure tree. Must be refused, never 'fixed'."""
    return _read("untagged_scanned.pdf")


@pytest.fixture
def layout_ground_truth() -> dict:
    """Load the snapshotted layout detection ground truth.

    Generated by: PYTHONPATH=src python tests/fixtures/snapshot_layout.py
    """
    gt_path = FIXTURES / "layout_ground_truth.json"
    if not gt_path.exists():
        pytest.skip(
            "Layout ground truth not found. "
            "Run: PYTHONPATH=src python tests/fixtures/snapshot_layout.py"
        )
    return json.loads(gt_path.read_text())


@pytest.fixture
def demo_pdf_bytes() -> bytes:
    """The demo PDF (sample_inaccessible.pdf) as bytes."""
    demo_path = Path(__file__).parent.parent / "demo" / "sample_inaccessible.pdf"
    if not demo_path.exists():
        pytest.skip("Demo PDF not found. Run: python demo/make_sample_pdf.py")
    return demo_path.read_bytes()


@pytest.fixture
def artifacts_dir() -> Path:
    """Path to the test artifacts directory for debug output."""
    ARTIFACTS.mkdir(exist_ok=True)
    return ARTIFACTS
