import type { Block, LineWidth, PdfDoc } from './types'

export const DEPARTMENTS = [
  'Accounts Payable Travel',
  'Benefits',
  'Budget Planning',
  'Bursar',
  'Capital Public Radio',
  'Employment Services',
  'Facilities Management',
  'OneCard',
  'Payroll',
  'Police Department',
  'Procurement',
  'Property Management',
  'Risk Management',
  'Space Management',
  'Student Employment',
  'UFSS',
  'University Print',
  'UTAPS',
] as const

/* ── Block builders — keep page layouts readable ───────────────── */

const line = (width: LineWidth = 'full'): Block => ({ kind: 'line', width })
const field = (): Block => ({ kind: 'field' })
const image = (imageId: string): Block => ({ kind: 'image', imageId })
const gap = (): Block => ({ kind: 'gap' })

const formBody = (): Block[] => [line(), line('mid'), gap(), field(), field(), field()]

/* ── Documents ─────────────────────────────────────────────────── */

export const DOCUMENTS: PdfDoc[] = [
  {
    id: 'travel-reimbursement',
    name: 'Travel Reimbursement Form.pdf',
    department: 'Accounts Payable Travel',
    updated: 'Mar 4, 2026',
    size: '412 KB',
    status: 'needs-review',
    pages: [
      { kicker: 'Accounts Payable Travel', title: 'Travel Reimbursement Request', blocks: [line(), line('mid'), gap(), field(), field()] },
      { kicker: 'Section 2', title: 'Trip Details & Receipts', blocks: [line('short'), image('img-1'), line(), line('mid'), field()] },
      { kicker: 'Section 3', title: 'Expense Itemization', blocks: formBody() },
      { kicker: 'Section 4', title: 'Financial Aid Instructions', blocks: [line(), line('mid'), gap(), line('short'), field()] },
      { kicker: 'Section 5', title: 'Signature Page', blocks: [line('mid'), gap(), field(), line('short')] },
    ],
    bookmarks: [
      { id: 'bm-t1', label: 'Trip Details', target: 2, correctTarget: 2 },
      { id: 'bm-t2', label: 'Expense Itemization', target: 3, correctTarget: 3 },
      { id: 'bm-t3', label: 'Financial Aid Instructions', target: null, correctTarget: 4 },
      { id: 'bm-t4', label: 'Signature Page', target: 2, correctTarget: 5 },
    ],
    issues: [
      {
        id: 'travel-alt-1',
        type: 'alt',
        page: 2,
        severity: 'High',
        imageId: 'img-1',
        imageLabel: 'Image 1',
        suggestedAlt: 'Students walking outside a Sacramento State campus building.',
      },
      {
        id: 'travel-bm-1',
        type: 'bookmark',
        page: 4,
        severity: 'Medium',
        bookmarkId: 'bm-t3',
        bookmarkLabel: 'Financial Aid Instructions',
        problem: 'Bookmark target is missing or points to the wrong page.',
        suggestedFix: 'Link bookmark to Page 4, Financial Aid Instructions section.',
      },
      {
        id: 'travel-bm-2',
        type: 'bookmark',
        page: 5,
        severity: 'Medium',
        bookmarkId: 'bm-t4',
        bookmarkLabel: 'Signature Page',
        problem: 'Bookmark target is missing or points to the wrong page.',
        suggestedFix: 'Link bookmark to Page 5, Signature Page section.',
      },
    ],
  },

  {
    id: 'benefits-enrollment',
    name: 'Benefits Enrollment Form.pdf',
    department: 'Benefits',
    updated: 'Feb 19, 2026',
    size: '288 KB',
    status: 'issues-found',
    pages: [
      { kicker: 'Benefits', title: 'Benefits Enrollment', blocks: [line('short'), image('img-1'), line(), field()] },
      { kicker: 'Section 2', title: 'Plan Comparison', blocks: formBody() },
      { kicker: 'Section 3', title: 'Dependent Information', blocks: [line(), field(), field()] },
    ],
    bookmarks: [
      { id: 'bm-b1', label: 'Enrollment Overview', target: 1, correctTarget: 1 },
      { id: 'bm-b2', label: 'Plan Comparison Chart', target: null, correctTarget: 2 },
      { id: 'bm-b3', label: 'Dependent Information', target: 3, correctTarget: 3 },
    ],
    issues: [
      {
        id: 'benefits-alt-1',
        type: 'alt',
        page: 1,
        severity: 'High',
        imageId: 'img-1',
        imageLabel: 'Image 1',
        suggestedAlt: 'Chart comparing monthly premiums across three CSU health plans.',
      },
      {
        id: 'benefits-bm-1',
        type: 'bookmark',
        page: 2,
        severity: 'Medium',
        bookmarkId: 'bm-b2',
        bookmarkLabel: 'Plan Comparison Chart',
        problem: 'Bookmark target is missing or points to the wrong page.',
        suggestedFix: 'Link bookmark to Page 2, Plan Comparison section.',
      },
    ],
  },

  {
    id: 'payroll-direct-deposit',
    name: 'Payroll Direct Deposit.pdf',
    department: 'Payroll',
    updated: 'Mar 11, 2026',
    size: '196 KB',
    status: 'needs-review',
    pages: [
      { kicker: 'Payroll', title: 'Direct Deposit Authorization', blocks: [line(), line('mid'), gap(), field(), field()] },
      { kicker: 'Section 2', title: 'Account Verification', blocks: [line('short'), image('img-1'), line('mid'), field()] },
      { kicker: 'Section 3', title: 'Voided Check Sample', blocks: [line('short'), image('img-2'), line('mid')] },
      { kicker: 'Section 4', title: 'Financial Aid Instructions', blocks: [line(), line('mid'), gap(), field()] },
      { kicker: 'Section 5', title: 'Signature Page', blocks: [line('mid'), gap(), field(), line('short')] },
    ],
    bookmarks: [
      { id: 'bm-p1', label: 'Account Verification', target: 2, correctTarget: 2 },
      { id: 'bm-p2', label: 'Voided Check Sample', target: 3, correctTarget: 3 },
      { id: 'bm-p3', label: 'Financial Aid Instructions', target: null, correctTarget: 4 },
      { id: 'bm-p4', label: 'Signature Page', target: 3, correctTarget: 5 },
    ],
    issues: [
      {
        id: 'payroll-alt-1',
        type: 'alt',
        page: 2,
        severity: 'High',
        imageId: 'img-1',
        imageLabel: 'Image 1',
        suggestedAlt: 'Students walking outside a Sacramento State campus building.',
      },
      {
        id: 'payroll-alt-2',
        type: 'alt',
        page: 3,
        severity: 'High',
        imageId: 'img-2',
        imageLabel: 'Image 2',
        suggestedAlt: 'Sample voided check with routing and account numbers labeled.',
      },
      {
        id: 'payroll-bm-1',
        type: 'bookmark',
        page: 4,
        severity: 'Medium',
        bookmarkId: 'bm-p3',
        bookmarkLabel: 'Financial Aid Instructions',
        problem: 'Bookmark target is missing or points to the wrong page.',
        suggestedFix: 'Link bookmark to Page 4, Financial Aid Instructions section.',
      },
      {
        id: 'payroll-bm-2',
        type: 'bookmark',
        page: 5,
        severity: 'Medium',
        bookmarkId: 'bm-p4',
        bookmarkLabel: 'Signature Page',
        problem: 'Bookmark target is missing or points to the wrong page.',
        suggestedFix: 'Link bookmark to Page 5, Signature Page section.',
      },
    ],
  },

  {
    id: 'parking-permit-appeal',
    name: 'Parking Permit Appeal.pdf',
    department: 'UTAPS',
    updated: 'Jan 28, 2026',
    size: '154 KB',
    status: 'issues-found',
    pages: [
      { kicker: 'UTAPS', title: 'Parking Citation Appeal', blocks: [line(), line('mid'), gap(), field(), field()] },
      { kicker: 'Section 2', title: 'Supporting Evidence', blocks: [line('short'), image('img-1'), field()] },
    ],
    bookmarks: [
      { id: 'bm-u1', label: 'Appeal Instructions', target: 1, correctTarget: 1 },
      { id: 'bm-u2', label: 'Supporting Evidence', target: null, correctTarget: 2 },
    ],
    issues: [
      {
        id: 'utaps-alt-1',
        type: 'alt',
        page: 2,
        severity: 'High',
        imageId: 'img-1',
        imageLabel: 'Image 1',
        suggestedAlt: 'Map of Sacramento State parking structures with permit zones shaded.',
      },
      {
        id: 'utaps-bm-1',
        type: 'bookmark',
        page: 2,
        severity: 'Medium',
        bookmarkId: 'bm-u2',
        bookmarkLabel: 'Supporting Evidence',
        problem: 'Bookmark target is missing or points to the wrong page.',
        suggestedFix: 'Link bookmark to Page 2, Supporting Evidence section.',
      },
    ],
  },

  {
    id: 'purchase-requisition',
    name: 'Purchase Requisition.pdf',
    department: 'Procurement',
    updated: 'Mar 2, 2026',
    size: '332 KB',
    status: 'needs-review',
    pages: [
      { kicker: 'Procurement', title: 'Purchase Requisition', blocks: [line(), gap(), field(), field(), field()] },
      { kicker: 'Section 2', title: 'Vendor Information', blocks: [line('short'), image('img-1'), field()] },
    ],
    bookmarks: [
      { id: 'bm-pr1', label: 'Requisition Details', target: 1, correctTarget: 1 },
      { id: 'bm-pr2', label: 'Vendor Information', target: 1, correctTarget: 2 },
    ],
    issues: [
      {
        id: 'proc-alt-1',
        type: 'alt',
        page: 2,
        severity: 'High',
        imageId: 'img-1',
        imageLabel: 'Image 1',
        suggestedAlt: 'Flowchart showing the four approval stages of a purchase requisition.',
      },
      {
        id: 'proc-bm-1',
        type: 'bookmark',
        page: 2,
        severity: 'Medium',
        bookmarkId: 'bm-pr2',
        bookmarkLabel: 'Vendor Information',
        problem: 'Bookmark target is missing or points to the wrong page.',
        suggestedFix: 'Link bookmark to Page 2, Vendor Information section.',
      },
      {
        id: 'proc-alt-2',
        type: 'alt',
        page: 2,
        severity: 'Low',
        imageId: 'img-1',
        imageLabel: 'Image 1 (decorative rule)',
        suggestedAlt: 'Decorative divider — mark as artifact so screen readers skip it.',
      },
    ],
  },

  {
    id: 'onecard-replacement',
    name: 'OneCard Replacement Request.pdf',
    department: 'OneCard',
    updated: 'Dec 12, 2025',
    size: '121 KB',
    status: 'remediated',
    pages: [{ kicker: 'OneCard', title: 'OneCard Replacement Request', blocks: [line(), line('mid'), gap(), field(), field()] }],
    bookmarks: [{ id: 'bm-o1', label: 'Replacement Instructions', target: 1, correctTarget: 1 }],
    issues: [],
  },

  {
    id: 'student-employment-hire',
    name: 'Student Assistant Hire Packet.pdf',
    department: 'Student Employment',
    updated: 'Feb 6, 2026',
    size: '540 KB',
    status: 'issues-found',
    pages: [
      { kicker: 'Student Employment', title: 'Student Assistant Hire Packet', blocks: [line(), gap(), field(), field()] },
      { kicker: 'Section 2', title: 'Work Authorization', blocks: [line('short'), image('img-1'), field(), line('mid')] },
      { kicker: 'Section 3', title: 'Signature Page', blocks: [line('mid'), gap(), field()] },
    ],
    bookmarks: [
      { id: 'bm-s1', label: 'Work Authorization', target: 2, correctTarget: 2 },
      { id: 'bm-s2', label: 'Signature Page', target: null, correctTarget: 3 },
    ],
    issues: [
      {
        id: 'stuemp-alt-1',
        type: 'alt',
        page: 2,
        severity: 'High',
        imageId: 'img-1',
        imageLabel: 'Image 1',
        suggestedAlt: 'Example of an acceptable work authorization document with fields labeled.',
      },
      {
        id: 'stuemp-bm-1',
        type: 'bookmark',
        page: 3,
        severity: 'Medium',
        bookmarkId: 'bm-s2',
        bookmarkLabel: 'Signature Page',
        problem: 'Bookmark target is missing or points to the wrong page.',
        suggestedFix: 'Link bookmark to Page 3, Signature Page section.',
      },
    ],
  },

  {
    id: 'facilities-work-order',
    name: 'Facilities Work Order.pdf',
    department: 'Facilities Management',
    updated: 'Nov 30, 2025',
    size: '203 KB',
    status: 'remediated',
    pages: [{ kicker: 'Facilities Management', title: 'Facilities Work Order', blocks: [line(), gap(), field(), field(), field()] }],
    bookmarks: [{ id: 'bm-f1', label: 'Work Order Instructions', target: 1, correctTarget: 1 }],
    issues: [],
  },

  {
    id: 'risk-incident-report',
    name: 'Incident Report Form.pdf',
    department: 'Risk Management',
    updated: 'Jan 15, 2026',
    size: '267 KB',
    status: 'needs-review',
    pages: [
      { kicker: 'Risk Management', title: 'Incident Report', blocks: [line(), line('mid'), gap(), field(), field()] },
      { kicker: 'Section 2', title: 'Incident Location', blocks: [line('short'), image('img-1'), field()] },
    ],
    bookmarks: [
      { id: 'bm-r1', label: 'Reporting Instructions', target: 1, correctTarget: 1 },
      { id: 'bm-r2', label: 'Incident Location', target: 1, correctTarget: 2 },
    ],
    issues: [
      {
        id: 'risk-alt-1',
        type: 'alt',
        page: 2,
        severity: 'High',
        imageId: 'img-1',
        imageLabel: 'Image 1',
        suggestedAlt: 'Campus map with numbered zones for identifying an incident location.',
      },
      {
        id: 'risk-bm-1',
        type: 'bookmark',
        page: 2,
        severity: 'Medium',
        bookmarkId: 'bm-r2',
        bookmarkLabel: 'Incident Location',
        problem: 'Bookmark target is missing or points to the wrong page.',
        suggestedFix: 'Link bookmark to Page 2, Incident Location section.',
      },
    ],
  },

  {
    id: 'print-job-request',
    name: 'Print Job Request.pdf',
    department: 'University Print',
    updated: 'Feb 24, 2026',
    size: '178 KB',
    status: 'issues-found',
    pages: [
      { kicker: 'University Print', title: 'Print Job Request', blocks: [line(), gap(), field(), field()] },
      { kicker: 'Section 2', title: 'Proof Approval', blocks: [line('short'), image('img-1'), field()] },
    ],
    bookmarks: [
      { id: 'bm-up1', label: 'Job Specifications', target: 1, correctTarget: 1 },
      { id: 'bm-up2', label: 'Proof Approval', target: null, correctTarget: 2 },
    ],
    issues: [
      {
        id: 'print-alt-1',
        type: 'alt',
        page: 2,
        severity: 'High',
        imageId: 'img-1',
        imageLabel: 'Image 1',
        suggestedAlt: 'Print proof showing trim, bleed, and safety margins on a campus flyer.',
      },
      {
        id: 'print-bm-1',
        type: 'bookmark',
        page: 2,
        severity: 'Medium',
        bookmarkId: 'bm-up2',
        bookmarkLabel: 'Proof Approval',
        problem: 'Bookmark target is missing or points to the wrong page.',
        suggestedFix: 'Link bookmark to Page 2, Proof Approval section.',
      },
    ],
  },
]
